# Generated by Django 5.0 on 2023-12-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0008_product_product_image3_product_product_image4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=40),
        ),
    ]
